- name: Create Ansible User
  hosts: all
  become: true
  tasks:
    - name: Create Ansible User on hosts
      ansible.builtin.user:
        name: ansible
        password: "{{ ansible_password }}"
    - name: add sudo group rights for deployment user
      lineinfile:
        dest: /etc/sudoers.d/ansible
        regexp: "^ansible"
        line: "ansible ALL=(ALL) NOPASSWD: ALL"
        state: present
