- name: Testing an array
  hosts: ajo
  tasks:
    - name: Print array
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: ["one", "two", "three"]
    - name: Print another array using subkeys of var
      ansible.builtin.debug:
        msg: "{{ item.src }}"
        msg: "{{ item.dest }}"
      loop:
        - { src: "/tmp/lets_say_ssh_config", dest: "/etc/ssh/another_ssh_config" }