- name: Start Docker Containers
  hosts: fcvault
  tasks:
    - name: Echo Command when containers are down
      ansible.builtin.command: >
        /bin/echo "docker start beautiful_gould; docker start watchtower ; docker start vaultwarden"
      register: response
    - name: Print result
      ansible.builtin.debug:
        var: response
