- name: Start Docker Containers
  hosts: fcvault
  tasks:
    - name: Start Containers
      ansible.builtin.command: /bin/echo "docker start beautiful_gould ; docker start watchtower ; docker start vaultwarden"
      register: response
    - name: Print result
      ansible.builtin.debug:
        var: response
    - name: Check if containers are running
      ansible.builtin.command: docker ps -a
      register: docker_ps
    - name: Print Status
      ansible.builtin.debug:
        var: docker_ps
