- name: Start Docker Containers
  hosts: fcvault
  tasks:
    - name: Check Containers Status
      ansible.builtin.command: docker ps -a
      register: containers_status
    - name: Start Containers when stopped
      ansible.builtin.command: /bin/echo "docker start beautiful_gould ; docker start watchtower ; docker start vaultwarden"
      when: containers_status.stdout.find('stopped')
    - name: Check if containers are running
      ansible.builtin.command: docker ps -a
      register: docker_ps
    - name: Print Status
      ansible.builtin.debug:
        var: containers_status
